import 'package:envied/envied.dart';

part 'env.g.dart';

/// Compile-time environment variables — generated by envied.
///
/// Values come from `.env` at build time. Never committed to source.
/// Run `flutter pub run build_runner build` after creating/changing `.env`.
@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'SUPABASE_PROJECT_ID')
  static const String supabaseProjectId = _Env.supabaseProjectId;

  @EnviedField(varName: 'SUPABASE_ANON_PUBLIC', obfuscate: true)
  static final String supabaseAnonKey = _Env.supabaseAnonKey;

  /// Supabase URL derived from project ID.
  static String get supabaseUrl => 'https://$supabaseProjectId.supabase.co';
}
